name: flutter_application_1
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.30.1
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5 
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.30.1
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_bloc: ^9.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/